<?php
// +----------------------------------------------------------------------+
// | VSwoole FrameWork                                                    |
// +----------------------------------------------------------------------+
// | Not Decline To Shoulder a Responsibility                             |
// +----------------------------------------------------------------------+
// | zengzhifei@outlook.com                                               |
// +----------------------------------------------------------------------+

namespace vSwoole\application\server;


use vSwoole\application\server\logic\KafkaLogic;
use vSwoole\core\server\KafkaServer;
use vSwoole\library\common\Config;
use vSwoole\library\common\Inotify;
use vSwoole\library\common\Process;
use vSwoole\library\common\Task;

class Kafka extends KafkaServer
{
    /**
     * 启动服务器
     * WebSocket constructor.
     * @param array $connectOptions
     * @param array $configOptions
     * @throws \ReflectionException
     */
    public function __construct(array $connectOptions = [], array $configOptions = [])
    {
        parent::__construct($connectOptions, $configOptions); // TODO: Change the autogenerated stub
    }

    /**
     * 主进程启动回调函数
     * @param \swoole_server $server
     * @throws \Exception
     */
    public function onStart(\swoole_server $server)
    {
        parent::onStart($server); // TODO: Change the autogenerated stub
    }

    /**
     * 管理进程启动回调函数
     * @param \swoole_server $server
     */
    public function onManagerStart(\swoole_server $server)
    {
        parent::onManagerStart($server); // TODO: Change the autogenerated stub

        //DEBUG模式下，监听文件变化自动重启
        if (Config::loadConfig('config', true)->get('is_debug')) {
            Process::getInstance()->add(function ($process) use ($server) {
                $process->name(VSWOOLE_KAFKA_SERVER . ' inotify');
                Inotify::getInstance()->watch([VSWOOLE_CONFIG_PATH, VSWOOLE_APP_SERVER_PATH . 'logic/KafkaLogic.php'], function () use ($server) {
                    $server->reload();
                });
            });
            Process::signalProcess(false);
        }
    }

    /**
     * 工作进程启动回调函数
     * @param \swoole_server $server
     * @param int $worker_id
     */
    public function onWorkerStart(\swoole_server $server, int $worker_id)
    {
        parent::onWorkerStart($server, $worker_id); // TODO: Change the autogenerated stub

        //引入逻辑代码
        $this->logic = new KafkaLogic($server);
    }

    /**
     * 异步任务执行回调函数
     * @param \swoole_server $server
     * @param int $task_id
     * @param int $src_worker_id
     * @param $data
     */
    public function onTask(\swoole_server $server, int $task_id, int $src_worker_id, $data)
    {
        parent::onTask($server, $task_id, $src_worker_id, $data); // TODO: Change the autogenerated stub

        //执行异步任务
        Task::execute($server, $data);
    }

    /**
     * 异步任务执行完成回调函数
     * @param \swoole_server $server
     * @param int $task_id
     * @param $data
     */
    public function onFinish(\swoole_server $server, int $task_id, $data)
    {
        parent::onFinish($server, $task_id, $data); // TODO: Change the autogenerated stub

        // 执行异步任务完成回调函数
        Task::finish($data);
    }

    /**
     * 客户端断开回调函数
     * @param \swoole_server $server
     * @param int $fd
     * @param int $reactor_id
     */
    public function onClose(\swoole_server $server, int $fd, int $reactor_id)
    {
        parent::onClose($server, $fd, $reactor_id); // TODO: Change the autogenerated stub
    }

    /**
     * 主进程结束回调函数
     * @param \swoole_server $server
     * @throws \Exception
     */
    public function onShutdown(\swoole_server $server)
    {
        parent::onShutdown($server); // TODO: Change the autogenerated stub
    }
}